name: Read Issue Content and Labels
description: Acton to process a new issue
# the main calling action must have the following permissions as well. 

permissions:
  issues: write
  pull-requests: write
  contents: write  # Allows creating branches, pushing changes to repositories

runs:
    using: 'composite'
    steps:

#      - name: cmip-ld library
#        id: install-cmipld
#        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main

      - name: Checkout repository
        uses: actions/checkout@v4       
        with:
          fetch-depth: 0

      - name: Configure Git for simple push
        run: git config --global push.default simple
        shell: bash

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run Python script
        id: run_python
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
          # pipe should preseve newline properties for multilines
          ISSUE_SUBMITTER: ${{ github.event.issue.user.login }}
          # ${{ github.actor }} 
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }} # We need this to update the issue

        run: |
          python new_issue.py

          OUTPUT=$(find . -type f -name "*.json" | sed -n '2p')
          echo "json=$OUTPUT" >> $GITHUB_OUTPUT
          echo "THE OUTPUT JSON FILES PRESENT ARE $OUTPUT"

        shell: bash
        continue-on-error: false

      - name: Switch to src-data branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch origin src-data
          git checkout src-data
        shell: bash

      - name: Commit new file
        run: |
          git add "${{ steps.run_python.outputs.json }}"
          git commit -m "New JSON file added from issue form." || echo "No changes to commit."
          git push origin src-data
        shell: bash
