name: Experiment Submission
description: Submit a new experiment definition
title: "[EXPERIMENT] New Submission"
labels: ['experiment', 'cv-submission']
body:
  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP code name
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: input
    id: origin
    attributes:
      label: Origin
      description: The origin of the model family
      placeholder: "e.g. NCAR (National Center for Atmospheric Research)"
    validations:
      required: true
