name: "Add/Modify: Frequency"
description: Add or modify a frequency in WCRP Universe
title: "Add/Modify: Frequency: <Type frequency name here>"
labels: ['delta', 'frequency', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Frequency

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. mon"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Monthly"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
