name: "Add/Modify: frequency"
description: Add or modify frequency in WCRP Universe
title: "Add/Modify: frequency: <Type activity name here>"
labels: ['frequency', 'cv-submission']
body:
  - type: dropdown
    id: modification
    attributes:
      label: Issue Type
      description: Create new or modify existing issue
      options:
        - "New"
        - "Modify"
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: Experiment ID
      description: Unique identifier (lowercase, hyphen-separated)
      placeholder: "e.g. aera-mip"
    validations:
      required: true

  - type: input
    id: long_name
    attributes:
      label: Long Name
      description: Longer human readable name
    validations:
      required: true

  - type: input
    id: unit
    attributes:
      label: Unit
      description: The unit of measurement
      placeholder: "e.g. hour"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Data type
      options:
        - "wcrp"
        - "esgvoc"
        - "universal"
    validations:
      required: true
