name: "Add/Modify: license"
description: Add or modify license in WCRP Universe
title: "Add/Modify: license: <Type activity name here>"
labels: ['license', 'cv-submission']
body:
  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: URL
      description: A link to the associated research paper
      placeholder: "e.g. https://wcrp-cmip.org/"
