name: "Add/Modify: License"
description: Add or modify a license in WCRP Universe
title: "Add/Modify: License: <Type license name here>"
labels: ['delta', 'license', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: License

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. cc-by-4.0"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. CC BY 4.0"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
