name: "Add/Modify: MIP"
description: Add or modify a MIP in WCRP Universe
title: "Add/Modify: MIP: <Type MIP name here>"
labels: ['delta', 'mip', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: MIP

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. cmip7"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. CMIP7"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
