name: Experiment Submission
description: Submit a new experiment definition
title: "[EXPERIMENT] New Submission"
labels: ['experiment', 'cv-submission']
body:
  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP code name
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: URL
      description: A link to the associated research paper
      placeholder: "e.g. https://wcrp-cmip.org/"

  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Organisation changes

  - type: multiple fields
    id: members
    attributes:
      label: Members
      description: Organisation members

  - type: input
    id: status
    attributes:
      label: Status
      description: Organisation status
      placeholder: "e.g. active"
