name: "Add/Modify: Model Component Type"
description: Add or modify a model component type in WCRP Universe
title: "Add/Modify: Model Component Type: <Type component name here>"
labels: ['delta', 'model-component-type', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Model Component Type

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. atmosphere"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Atmosphere"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
