name: "Add/Modify: model_family"
description: Add or modify model_family in WCRP Universe
title: "Add/Modify: model_family: <Type activity name here>"
labels: ['model_family', 'cv-submission']
body:
  - type: dropdown
    id: modification
    attributes:
      label: Modify
      description: Create new or modify existing issue
      options:
        - "New"
        - "Modify"
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: Experiment ID
      description: Unique identifier (lowercase, hyphen-separated)
      placeholder: "e.g. aera-mip"
    validations:
      required: true

  - type: input
    id: origin
    attributes:
      label: Origin
      description: The origin of the model family
      placeholder: "e.g. NCAR (National Center for Atmospheric Research)"
    validations:
      required: true

  - type: dropdown
    id: permissible_realms
    attributes:
      multiple: true
      label: Permissible realms
      description: Available schemes for data production
      options:
        - "atmos"
        - "land"
        - "ocean"
        - "ocnbgchem"
        - "seaice"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Data type
      options:
        - "wcrp"
        - "esgvoc"
        - "universal"
    validations:
      required: true
