name: "Add/Modify: Native Vertical Grid Coordinate"
description: Add or modify a vertical grid coordinate in WCRP Universe
title: "Add/Modify: Vertical Coordinate: <Type coordinate here>"
labels: ['delta', 'vertical-coordinate', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Native Vertical Grid Coordinate

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. pressure"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Pressure"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
