name: "Add/Modify: Native Vertical Grid Units"
description: Add or modify vertical grid units in WCRP Universe
title: "Add/Modify: Vertical Units: <Type units here>"
labels: ['delta', 'vertical-units', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Native Vertical Grid Units

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. meters"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Meters"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
