name: "Add/Modify: Native Horizontal Grid Type"
description: Add or modify a native horizontal grid type in WCRP Universe
title: "Add/Modify: Grid Type: <Type grid type here>"
labels: ['delta', 'grid-type', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Native Horizontal Grid Type

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. regular-lat-lon"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Regular Lat-Lon"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
