name: "Add/Modify: native_horizontal_grid_type"
description: Add or modify native_horizontal_grid_type in WCRP Universe
title: "Add/Modify: native_horizontal_grid_type: <Type activity name here>"
labels: ['native_horizontal_grid_type', 'cv-submission']
body:
  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true
