name: "Add/Modify: organisation"
description: Add or modify organisation in WCRP Universe
title: "Add/Modify: organisation: <Type activity name here>"
labels: ['organisation', 'cv-submission']
body:
  - type: dropdown
    id: modification
    attributes:
      label: Issue Type
      description: Create new or modify existing issue
      options:
        - "New"
        - "Modify"
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: URL
      description: A link to the associated research paper
      placeholder: "e.g. https://wcrp-cmip.org/"

  - type: input
    id: id
    attributes:
      label: Experiment ID
      description: Unique identifier (lowercase, hyphen-separated)
      placeholder: "e.g. aera-mip"
    validations:
      required: true

  - type: input
    id: acronyms
    attributes:
      label: Acronyms
      description: Organisation acronyms
      placeholder: "e.g. AER"

  - type: input
    id: aliases
    attributes:
      label: Aliases
      description: Organisation aliases

  - type: input
    id: established
    attributes:
      label: Established
      description: Year that organisation was established
      placeholder: "e.g. 1977"
    validations:
      required: true

  - type: input
    id: kind
    attributes:
      label: Kind
      description: The kind of organisation
      placeholder: "e.g. Facility"
    validations:
      required: true

  - type: input
    id: labels
    attributes:
      label: Labels
      description: Organisation labels
      placeholder: "e.g. Osservatorio Astronomico di Roma"

  - type: input
    id: location_lat
    attributes:
      label: Latitude
      description: Location latitude in degrees
    validations:
      required: true

  - type: input
    id: location_lon
    attributes:
      label: Longitude
      description: Location longitude in degrees
    validations:
      required: true

  - type: input
    id: location_city
    attributes:
      label: City
      description: City
    validations:
      required: true

  - type: input
    id: location_country
    attributes:
      label: Country
      description: Country
    validations:
      required: true

  - type: input
    id: ror
    attributes:
      label: ROR
      description: Research organisation registry
      placeholder: "e.g. 02hnp4676"
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Organisation changes

  - type: input
    id: status
    attributes:
      label: Status
      description: Organisation status
      placeholder: "e.g. active"

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Data type
      options:
        - "wcrp"
        - "esgvoc"
        - "universal"
    validations:
      required: true
