name: "Add: Institution"
description: "Type: Institution"
title: "Add: Institution: <Type Institution Acronym Here>"
labels: ['alpha', 'institution', 'organisation', 'universe', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        #### 
        ## Adding a new Institution. 
        
        Please fill in the information below.

  - type: dropdown
    id: category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
        - "institution"
      default: 0
    validations:
      required: true

  - type: input
    id: label
    attributes:
      label: Acronym
      description: |
        A short acronym from which your institution can be identified with. 
        
        Note: This name must be unique across all organisations and cannot be changed once data is published with it.
      placeholder: "e.g. UoYork MOHC CMIP-IPO"
    validations:
      required: true

  - type: input
    id: long_label
    attributes:
      label: Full name of the organisation
      description: |
        Please provide a full name for the organisation to perform checks and help users understand the acronym.
      placeholder: "e.g. University of York (UK)"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: ROR
      description: |
        To help maintain traceability we are making use of the research organisation registry (ROR). This allows us to generate a unique id for each institution and extract a detailed log of history.
        
        To get your organisation ROR number visit ror.org and search. If your organisation is not registered please register it first.
        
        If an open request exists on ROR but no number issued yet paste the reference URL here instead.
      placeholder: "e.g. 04m01e293"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Other Notes
      description: |
        Generally this section will remain empty but additional notes (e.g. source_id submissions using this institution) can be referenced here.
