name: "Add/Modify: product"
description: Add or modify product in WCRP Universe
title: "Add/Modify: product: <Type activity name here>"
labels: ['product', 'cv-submission']
body:
  - type: dropdown
    id: modification
    attributes:
      label: Issue Type
      description: Create new or modify existing issue
      options:
        - "New"
        - "Modify"
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation key
      description: CMIP acronym
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: Label
      description: Human-readable name
      placeholder: "e.g. Historical"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed scientific description
      placeholder: "Provide comprehensive description"
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: id
      description: Unique identifier (lowercase, hyphen-separated)
      placeholder: "e.g. aera-mip"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Data type
      options:
        - "wcrp"
        - "esgvoc"
        - "universal"
    validations:
      required: true
