name: "Add/Modify: Product"
description: Add or modify a product type in WCRP Universe
title: "Add/Modify: Product: <Type product name here>"
labels: ['delta', 'product', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Product

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. model-output"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Model Output"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
