name: "Add/Modify: Realm"
description: Add or modify a realm in WCRP Universe
title: "Add/Modify: Realm: <Type realm name here>"
labels: ['delta', 'realm', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Realm

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier (lowercase)
      placeholder: "e.g. atmos"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. Atmosphere"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
