name: "Add/Modify: Resolution"
description: Add or modify a resolution in WCRP Universe
title: "Add/Modify: Resolution: <Type resolution here>"
labels: ['delta', 'resolution', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        # Add/Modify: Resolution

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Type
      description: New or modify existing
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true

  - type: input
    id: validation_key
    attributes:
      label: Validation Key
      description: Unique identifier
      placeholder: "e.g. 100km"
    validations:
      required: true

  - type: input
    id: ui_label
    attributes:
      label: UI Label
      description: Full name
      placeholder: "e.g. 100 km"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description
